### ISSUE TITLE
Define IMP-

### ISSUE THREAD

**Issue by wimmers** [wimmers/poly-reductions#13]
We need to define `IMP-`. The starting point is `IMP` from the distribution.

## Details
We plan to use a slightly stripped-down version of the language `IMP` found in the Isabelle distribution
as our computation model.
The main differences are that arithmetic expressions cannot be nested and that Boolean expressions are limited
to comparison against 0.

### IMP- Features

```
r=a+b
r=a*b
r=<const>
if r!=0 then <cmd> else  <cmd>, 
while (r!=0) <cmd>
 <cmd>;  <cmd>
skip
```

The looping construct is useful because we can always add a compilation step that unravels a more complex Boolean condition in the while-loop beforehand.

**Comment by notiho** [comment]
Hi

**Comment by notiho** [comment]
I made pull request #23 for this.
