### ISSUE TITLE
Reduction from IMP- to IMP--

### ISSUE THREAD

**Issue by notiho** [wimmers/poly-reductions#28]
Since the reduction from IMP-- to SAS+ appears not that easy, @mabdula and I think that it makes sense to solve #8 by going the route IMP-  -> IMP-- -> SAS+ . 
This would probably involve something like bit-blasting. The reduction should be given a maximal number of bits for each register, and then simulate IMP- registers with multiple IMP-- registers, each holding a single bit. Then, instructions of the form `x ::= y + z` that are missing in IMP-- can be replaced by a binary addition (accordingly for subtraction), using only increments and decrements existing in IMP--.

**Comment by maxhaslbeck** [comment]
closed by merged PR #25
